### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by nyalldawson** [PeterHorsbollMoller/mbMapInfoRasterTool#1]
What license are the files in the repository published under?

**Comment by PeterHorsbollMoller** [comment]
That's a question I haven't really given a lot of thought. But I guess it should be dealt with.

I looked at the different types described here: https://fossbytes.com/open-sources-license-type/

I'm leaning towards the MIT license. Any comments?

**Comment by nyalldawson** [comment]
MIT is a great choice 👍

**Comment by PeterHorsbollMoller** [comment]
Is it enough to add a file with the license details to the repository?

**Comment by nyalldawson** [comment]
If the same license applies across the repo, then yes. If there's exceptions (e.g. folders under a different license), then they could have their own LICENSE file. There's not really any hard rules here, it's basically just a matter of doing whatever you think makes it clear to others how they are allowed to reuse the contents of this repository (without running into legal issues, that is!)

**Comment by PeterHorsbollMoller** [comment]
License file has now been added. 

Be aware, Nyall, that my examples really aren't the best option for taking advantage of the Raster SDK as I'm using MapBasic to call the .NET SDK. This is best done from .NET or using our recent GDAL MRR Reader.

**Comment by nyalldawson** [comment]
Thanks @PeterHorsbollMoller !

Do you have more info on the GDAL reader? My searching is coming up empty...
