### ISSUE TITLE
Unable to select coordinate system / projection with multi-ascii merge

### ISSUE THREAD

**Issue by davetownend** [PeterHorsbollMoller/mbMapInfoRasterTool#2]
Unable to use the multi-asc merge function due to exception related to coordinate system. Should the projection specification menu be started in order to select the coordinate system immediately after running the 'merge ASC files in folder(s)' functions? 

![ex_1_5_2](https://user-images.githubusercontent.com/33422537/60606865-0714f980-9db4-11e9-9de5-be0a50414cd7.PNG)

**Comment by PeterHorsbollMoller** [comment]
In version 1.6.1 "Merge ASC files in folder" has been added the Choose Coordsys dialog. I assume this issue therefor has been fixed. Are you maybe using v1.6.0 where this wasn't the case?

**Comment by davetownend** [comment]
Yes issue resolved in 1.6.1 thanks!
